version: "3"
services:
    app:
        container_name: express_react_app
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment: 
            DB_HOST: postgres
            NODE_ENV: production
            DB_NAME: shockbyte
            DB_USERNAME: postgres
            DB_PASSWORD: root
        links: 
            - db
        networks: 
            - app-network
        depends_on: 
            - db
    db:
        container_name: shockbyte_db
        image: postgres
        restart: always
        environment: 
            POSTGRES_DB: shockbyte
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        networks: 
            app-network:
                aliases: 
                    - postgres
        ports:
            - "5432:5432"
networks:
    app-network:
        driver: bridge
  